- hosts: localhost
  connection: local
  gather_facts: no
  sudo: no
  roles:
    - hnakamur.homebrew-packages
    - hnakamur.homebrew-cask-packages
  vars:
    homebrew_taps:
        -homebrew/apache
        -homebrew/php
        -caskroom/cask
        # -railwaycat/emacsmacport

    homebrew_repositories:
        -sanemat/font

    homebrew_packages:
        - { name: ansible }
        - { name: coreutils }
        - { name: ctag }
        - { name: curl }
        - { name: direnv }
        - { name: git }
        - { name: go }
        - { name: jq }
        - { name: lua }
        - { name: vim, install_options: with-lua }
        - { name: mysql }
        - { name: node }
        - { name: openssl }
        - { name: openssl, state: linked, install_options: force }
        - { name: phantomjs }
        - { name: python }
        - { name: rbenv }
        - { name: reattach-to user-namespace }
        - { name: ruby-build }
        - { name: source-highlight }
        - { name: sqlite }
        - { name: tmux }
        - { name: z }

    homebrew_cask_packages:
        - { name: airserver }
        - { name: android-studio }
        - { name: appcleaner }
        - { name: bartender }
        - { name: bettertouchtool }
        - { name: clarify }
        - { name: coteditor }
        - { name: delayedlauncher }
        - { name: emacs-mac }
        - { name: flux }
        - { name: google-japanese-ime }
        - { name: iterm2 }
        - { name: istatmenus }
        - { name: java }
        - { name: karabiner }
        - { name: keyboard-maestro }
        - { name: keyboardcleantool }
        - { name: lightningkeyboard }
        - { name: mou }
        - { name: onyx }
        - { name: path-finder }
        - { name: scapple }
        - { name: sourcetree }
        - { name: totals }
        - { name: xscope }
        - { name: xtrafinder }

    tasks:
        - name: 'make symlinks to under home dir'
          file: src={{ item }} dest=~/.{{ item | basename }} state=link force=yes
          with_fileglob:
            - home_symlinks/*

        - name: mkdir vim-neobundle dir
          file: path=~/.vim/bundle state=directory
          notify: install neobundle

        - name: Add tap the repository of homebrew
          homebrew_taps: tap={{ item }} state=present
          with_items: homebrew_taps

        - name: Updated homebrew
          homebrew: update_homebrew=yes

        # brew
        - name: Install the brew package
          homebrew: >
            name={{ item.name }}
            state={{ item.state | default('latest') }}
            install_options={{
                item.install_options | default() | join(',')
                if item.install_options is not string
                else item.install_options
            }}
          with_items: homebrew_packages
          register: brew_result
        - name: Create information destination directory of brew package
          file: path=brew_info state=directory
        - name: Save the information in the brew package
          shell: brew info {{ item }} > brew_info/{{ item }}
          with_items: brew_result.results | selectattr('changed') | map(attribute='item') | map(attribute='name') | list

        # cask
        - name: Install the homebrew-cask
          homebrew: name=brew-cask state=latest
        - name: Install the cask package
          homebrew_cask: name={{ item.name }} state={{ item.stete|default('installed') }}
          with_items: homebrew_cask_packages
          register: cask_result
        - name: Create information destination directory of cask package
          file: path=cask_info state=directory
        - name: Save the information in the cask package
          shell: brew cask info {{ item }} > cask_info/{{ item }}
          with_items: cask_result.results | selectattr('changed') | map(attribute='item') | map(attribute='name') | list

        # oh-my-zsh
        - name: Install the oh-my-zsh
          shell: curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh
          args:
            creates: ~/.oh-my-zsh/

        # Ricty
        - name: Install the xquartz for Ricty
          homebrew_cask: name=xquartz
        - name: Install the fontforge
          homebrew: name=fontforge
        - name: Install the Ricty
          homebrew: name=ricty
        - name: Copy the generated fot file
          shell: cp -f $(brew --cellar ricty)/*/share/fonts/Ricty*.ttf ~/Library/Fonts/
          args:
            creates: ~/Library/Fonts/Ricty-Bold.ttf
          notify: run fc-cache

    handlers:
        - name: run fc-cache
          sell: fc-cache -vf
        - name: install neobundle
          command: git clone git://github.com/Shougo/neobundle.vim ~/.vim/bundle/neobundle.vim
